name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'
        channel: 'stable'      
    - run: flutter pub get
    # - run: flutter test
    
    - name: Build Android APK
      run: flutter build apk

    # - name: Build iOS
    #   run: flutter build ios --release --no-codesign
    
    - name: Build Web
      run: flutter build web

    # for Uploading artifacts
    - uses: actions/upload-artifact@v4.3.6
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    # - uses: actions/upload-artifact@v4.3.6
    #   with:
    #     name: release-ios
    #     path: build/ios/iphoneos
    - uses: actions/upload-artifact@v4.3.6
      with:
        name: release-web
        path: build/web
